fix(darwin): add missing Foundation import to access JSONSerialization class
Fixes macOS compilation error by importing `Foundation` to access `JSONSerialization`.

Without this import (tested on macOS 15.5, Xcode Version 16.4):

```console
error: cannot find 'JSONSerialization' in scope
            let data = try JSONSerialization.data(withJSONObject: json)
```